### ISSUE TITLE
LanguageToolBear: Mention that language tool is a dependency 

### ISSUE THREAD

**Issue by sims1253** [coala/bear-docs#13]
And also where to get it:
https://languagetool.org/

**Comment by sils** [comment]
this should be done in the coala-bears repository, all contents here are generated.

See also coala/bear-docs#18

**Comment by sils** [comment]
i.e. change the doc comment there. Also @sims1253 why do we want to explicitly mention that if we already have dependency metadata? That's duplication and also leads to inconsistency right?

**Comment by adtac** [comment]
This is now mentioned in a section anyway: https://github.com/coala/bear-docs/blob/master/docs/LanguageToolBear.rst#dependencies

Closing
