### ISSUE TITLE
ClangFunctionDifferenceBear doesn't generate proper docs for whatever reason

### ISSUE THREAD

**Issue by adtac** [coala/bear-docs#14]
https://github.com/coala-analyzer/bear-docs/blob/master/docs/ClangFunctionDifferenceBear.rst

`counting_conditions` has memory addresses.

I'm temporary disabling docs generation for it.

**Comment by sils1297** [comment]
why disabling generation? We have an issue for this in coala already.

**Comment by adtac** [comment]
Because every commit will have unnecessary changes to that file. Makes each commit less readable.
