### ISSUE TITLE
JavaPMDBear is not found

### ISSUE THREAD

**Issue by rpau** [coala/bear-docs#21]
Hi,

When I run 

coala --show-bears --filter-by-language java

The JavaPMDBear not appears in the list. Any suggestion?

CPDBear
CheckstyleBear
FilenameBear
InferBear
InvalidLinkBear
KeywordBear
LineCountBear
LineLengthBear
SpaceConsistencyBear
coalaBear

**Comment by sils** [comment]
Interesting, which release? (coala -v)

**Comment by sils** [comment]
This issue was moved to coala/coala-bears#998
