### ISSUE TITLE
Would be neat to offer a default .coafile for each bear

### ISSUE THREAD

**Issue by sims1253** [coala/bear-docs#24]
So users could just copy paste it and change what they need different

**Comment by arnab1896** [comment]
@sims1253 ; i just have experience with newcomer issues. Should i go for this issue? Or is it a difficult one?

**Comment by Makman2** [comment]
shouldn't be too hard, it's about providing meaningful coafiles for single bears. Go ahead ;)

**Comment by arnab1896** [comment]
Thanks!

**Comment by jayvdb** [comment]
I suspect that the default `.coafile` should be part of the bear itself, either as raw metadata, or as a chunk of text.  If these chunks of text are in this repo, that wont be maintained, especially wont be maintained for multiple branches.

**Comment by arnab1896** [comment]
so, should i just add one .coafile in the coala-bears repo?

one giant .coafile with all the important parameters of multiple bears together?

**Comment by Makman2** [comment]
Rather one for each bear :+1:

Maybe we should introduce some `example` field for bears, so `MyBear.example = ...` and the user can see it in the docs^^ (just an idea)
