### ISSUE TITLE
Dependency version numbers

### ISSUE THREAD

**Issue by jayvdb** [coala/bear-docs#25]
The docs currently contain dependencies but not the required versions

difficulty/low

**Comment by ankit01ojha** [comment]
@jayvdb IMO , latest version of each dependency we'll be fine and since , the latest versions keep on changing so , it would be fine if only latest version should be downloaded :)

**Comment by jayvdb** [comment]
please see the many version related bugs we have in the coala-bears repo. The 'latest' version is definately not supported. It is our job as integrators to add value to the linters, and that means being careful about versions.
