### ISSUE TITLE
Add rultor yml!

### ISSUE THREAD

**Issue by sils** [coala/bear-docs#26]
So I can set up permissions such that only rultor may merge/push.

**Comment by incorrectusername** [comment]
hello @sils  , can you assign this to me?newcomer here ?how do i proceed?

**Comment by sils** [comment]
Hi,

please don't ping me personally for such things. Everyone can do them - and almost everyone pings me. If you don't address a person specifically you'll likely get help faster from other people!

(Don't worry, this is not a problem but keeping things general is usually a good policy :))

**Comment by sils** [comment]
Just copy https://github.com/coala/documentation/blob/master/.rultor.yml into this repo
