### ISSUE TITLE
PMD external ruleset

### ISSUE THREAD

**Issue by rpau** [coala/bear-docs#30]
Hi,

PMD can be configurable to use an external ruleset (provided by an external machine), which contains a subset of each ruleset. 

How can it be configured?

**Comment by Makman2** [comment]
Have you looked at the `PMDBear`? Though not sure whether it supports what you want :)

If not we move the issue to [coala/coala-bears](https://github.com/coala/coala-bears) to implement this feature :+1:

**Comment by rpau** [comment]
Yes, I looked to PMDBear documentation and [code](https://github.com/coala/coala-bears/blob/28d24b61ab455973a68500f55102400e928823ee/bears/java/JavaPMDBear.py).

Ok, feel free to move that issue.

**Comment by Makman2** [comment]
Moved to https://github.com/coala/coala-bears/issues/1361
