### ISSUE TITLE
Bear that uses HTML Tidy?

### ISSUE THREAD

**Issue by BlakeTurner** [coala/bear-docs#37]
Hello!

I'm new to the Coala community, but it looks pretty fantastic. We teach software development, and we're looking at integrating Coala into our project submission flow.

The HTMLLintBear is pretty good, but omits quite a few errors. Has anyone written a Bear that uses HTML Tidy? Its errors are significantly better.

Thanks in advance!

**Comment by meetmangukiya** [comment]
@BlakeTurner coala-bears is the repository where the bears are maintained/added, I've opened an issue there, if you wish to add anything else, comment on the new issue created there :)

**Comment by BlakeTurner** [comment]
Thanks!

**Comment by yash-nisar** [comment]
The issue has been moved to https://github.com/coala/coala-bears/issues/1520, so this can be closed.

**Comment by yash-nisar** [comment]
@meetmangukiya , can you close this issue ?
