### ISSUE TITLE
SCSSLintBear.rst: Some "meaning" in the table isn't formated correctly

### ISSUE THREAD

**Issue by Arsfiqball** [coala/bear-docs#40]
Checkout this file:
https://github.com/coala/bear-docs/blob/master/docs/SCSSLintBear.rst
For example, look at meaning of ``allow_filename_extension``
difficulty/newcomer

**Comment by jayvdb** [comment]
This requires a fix to https://github.com/coala/bear-docs/blob/master/language_generate.py , but this repo is deprecated as we want to move all the functionality into https://coala.io/#!/languages

**Comment by khanchi97** [comment]
Hello @jayvdb i think that the file https://github.com/coala/bear-docs/blob/master/language_generate.py  is only writing language and bears name in README.rst and providing link to bear's .rst file.So i think it may be other file in which some fix are required.
may be it is https://github.com/coala/bear-docs/blob/master/generate this file where some fix are required.Correct me if i'm wrong.
