### ISSUE TITLE
Update Github reference  link of each bear in Docs

### ISSUE THREAD

**Issue by RaiVaibhav** [coala/bear-docs#41]
Example: When we click on `CMakeLintBear` [In](https://github.com/coala/bear-docs/blob/master/docs/CMakeLintBear.rst) its giving [404 error webpage not found](https://github.com/coala/coala-bears/tree/master/bears/upload/CMakeLintBear/coalaCMakeLintBear/CMakeLintBear.py)

Note: Issue is only for GCI participant and assignee have to check and  update all the `.rst` file for each `Bear` in `Docs`

**Comment by RaiVaibhav** [comment]
maintainers add label `initiative/gci` , difficulty `newcomer`

**Comment by khanchi97** [comment]
@RaiVaibhav but I think repo  `bear-docs` is deprecated.So i think one shouldn't make any issue in this repo.

**Comment by RaiVaibhav** [comment]
Oh i did't know that BTW  how does you find iut that `bears-docs` is depricated

**Comment by prnvdixit** [comment]
@RaiVaibhav See description https://github.com/coala/bear-docs 😉

**Comment by RaiVaibhav** [comment]
Its funny that i did't read the basic description BTW thanks
